### ISSUE TITLE
exclusively use pillar data for vmc credentials

### ISSUE THREAD

**Issue by dhiltonp** [saltstack/salt-ext-modules-vmware#121]
We need to extract the function arguments used for vmc connections from pretty much everywhere, and change them to be pulled exclusively from pillar data. Conveniently this will mostly be deletions with just a few additions to `vmc_reques::call_api` :)

I suggest this structure, with these 6 parameters, but @waynew will have a good perspective on the normal naming and organization of pillar data.

```yaml
vmc_connection_details:
    console_host: hostname
    api_key: key
    org_id: UUID
    sddc_id: UUID
    nsx_host: hostname
    verify_ssl: False
```

`verify_ssl`: `(Optional) True/False or string with path to CA bundle. Defaults to True.`

We should also delete `cert` at the same time.

We will need to add documentation on how to find the correct values - generating an api key, browsing the UI to find the `org_id` and `nsx_host` etc.

This documentation will need to be linked in the module-level docstring of all vmc files.
