### ISSUE TITLE
How can I connect to multiple vCenter from the same minion?

### ISSUE THREAD

**Issue by abhi1693** [saltstack/salt-ext-modules-vmware#256]
I have added the configuration as follows on the master

top.sls
```
base:
  m1:
    - vc1
    - vc2
```

v1.sls
```
vmware_config:
  host: 192.168.100.10
  password: Password@123
  user: salt-test@vsphere.local
  verify_ssl: false
```

v2.sls
```
vmware_config:
  host: 192.168.100.20
  password: Password@123
  user: salt-test@vsphere.local
  verify_ssl: false
```

Now, I cannot seem to figure out how to call the commands using the specified credentials. For example, query datacenter list from `vc2`.
