### ISSUE TITLE
modules.dvswitch.remove_hosts, modules.dvswitch.add_hosts, dvswitch.update_hosts seem to operate on standard vSwitches, not Distributed vSwitches

### ISSUE THREAD

**Issue by ggiesen** [saltstack/salt-ext-modules-vmware#262]
I tried a state file that looks like this:

```
{% for host in ['hv01', 'hv02', 'hv03'] %}
saltmod_dvswitch_add_hosts_dvs-storage_{{ host }}:
  module.run:
    - vmware_dvswitch.add_hosts:
        - switch_name: DVS-STORAGE
        - datacenter_name: DC
        - cluster_name: CLUSTER
        - host_name: {{ host }}
        - nics:
            - vmnic2
            - vmnic3
{% endfor %}
```

And instead of attaching the hosts to a distributed vSwitch named `DVS-STORAGE`, it's actually creating a standard vSwitch on each host and attaching to that instead.
