### ISSUE TITLE
[BUG] esxi_host values aren't correctly used

### ISSUE THREAD

**Issue by waynew** [saltstack/salt-ext-modules-vmware#306]
Using a sample (new style) config:

```
saltext.vmware:
  host: host.example.com
  user: fnord
  password: my voice is my passport, verify me
  esxi_host:
    esxi.example.com:
      user: some_esxi_dude
      password: a totally different password
```

Running `salt-call vmware_esxi.get_role View` works, but `salt-call
vmware_esxi.get_role View esxi.example.com` does not -- `get_config` is not
correctly getting the user/password from the `esxi_host` portion of the salt
config.
