### ISSUE TITLE
vcenter profile could not be found in the Pillar 

### ISSUE THREAD

**Issue by ivanstcoe** [saltstack/salt-ext-modules-vmware#351]
I have defined the following config in the Pillars

```
   "saltext.vmware": {
        "vcenter": {
            "host": "xxx",
            "password": "xxx",
            "user": "xxx"
        }
    }

```
When i run the following state file i receive an error

```
get_esxi_advanced_config_info:
  module.run:
    - name: vmware_esxi.get_advanced_config
```

Error message:
```

local:
----------
          ID: get_esxi_firewall_config_info
    Function: module.run
        Name: vmware_esxi.get_all_firewall_configs
      Result: False
     Comment: Module function vmware_esxi.get_all_firewall_configs threw an exception. Exception: Cannot create service instance, VMware credentials incomplete.
     Started: 18:30:31.786613
    Duration: 41.309 ms
     Changes:
```
